version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - mynetwork
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
